"""add fitness coach tables

Revision ID: 20260611_100000
Revises: 20260610_090000
Create Date: 2026-06-11 10:00:00.000000

Note: ``Base.metadata.create_all`` in ``init_db()`` also creates these tables on
startup as a runtime safety net; this migration keeps the Alembic history and
environments reproducible (the versioned source of truth for clean deploys).

Creates the three Fitness_Coach tables: fitness_profiles (1:1 with users),
weight_entries (1:N) and workout_plans (1:N, at most one active per user).

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260611_100000'
down_revision: Union[str, None] = '20260610_090000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create fitness_profiles table (1:1 with users)
    op.create_table('fitness_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('weight_kg', sa.Float(), nullable=False),
        sa.Column('height_cm', sa.Float(), nullable=False),
        sa.Column('age', sa.Integer(), nullable=False),
        sa.Column('sex', sa.String(length=10), nullable=True),
        sa.Column('level', sa.String(length=20), nullable=False),
        sa.Column('equipment', sa.String(length=300), nullable=False),
        sa.Column('days_per_week', sa.Integer(), nullable=False),
        sa.Column('minutes_per_session', sa.Integer(), nullable=False),
        sa.Column('goal_type', sa.String(length=20), nullable=True),
        sa.Column('target_weight_kg', sa.Float(), nullable=True),
        sa.Column('target_date', sa.String(length=20), nullable=True),
        sa.Column('performance_target', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitness_profiles_user_id'), 'fitness_profiles', ['user_id'], unique=True)

    # Create weight_entries table (1:N with users)
    op.create_table('weight_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('weight_kg', sa.Float(), nullable=False),
        sa.Column('entry_date', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_entries_user_id'), 'weight_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_weight_entries_entry_date'), 'weight_entries', ['entry_date'], unique=False)

    # Create workout_plans table (1:N with users, at most one active)
    op.create_table('workout_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('goal_type', sa.String(length=20), nullable=False),
        sa.Column('structure', sa.Text(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_plans_active'), 'workout_plans', ['active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_plans_active'), table_name='workout_plans')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_table('workout_plans')

    op.drop_index(op.f('ix_weight_entries_entry_date'), table_name='weight_entries')
    op.drop_index(op.f('ix_weight_entries_user_id'), table_name='weight_entries')
    op.drop_table('weight_entries')

    op.drop_index(op.f('ix_fitness_profiles_user_id'), table_name='fitness_profiles')
    op.drop_table('fitness_profiles')
    # ### end Alembic commands ###
